version: "3"

services:

  # Reverse proxy
  traefik:
    container_name: traefik
    image: traefik:2.0.2
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yaml:/traefik.yaml:ro
      - ../traefik/etc:/etc/traefik/
      - ../traefik/log:/var/log/traefik/
    networks:
      - wp_network
    restart: unless-stopped

networks:
  wp_network:
    external:
      name: wp_network
