version: "2.4"

services:

  nginx-proxy:
    container_name: nginx-proxy
    image: jwilder/nginx-proxy:alpine
    volumes:
      - certs:/etc/nginx/certs:ro
      - vhost:/etc/nginx/vhost.d
      - dhparam:/etc/nginx/dhparam
      - html:/usr/share/nginx/html
      - conf:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
        - nginx-proxy
    restart: unless-stopped

  nginx-letsencrypt:
      container_name: nginx-proxy-le
      image: jrcs/letsencrypt-nginx-proxy-companion
      volumes:
        - certs:/etc/nginx/certs:rw
        - vhost:/etc/nginx/vhost.d
        - dhparam:/etc/nginx/dhparam
        - html:/usr/share/nginx/html
        - conf:/etc/nginx/conf.d
        - /var/run/docker.sock:/var/run/docker.sock:ro
      environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
      networks:
        - nginx-proxy
      restart: unless-stopped

networks:
  nginx-proxy:
    external:
      name: nginx-proxy

volumes:
  certs:
  vhost:
  dhparam:
  html:
  conf:
